
import './globals.css';
import NavBar from './NavBar';

export const metadata = {
  title: 'Sheik Gulfaan',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
  
}


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="manifest" href="/site.webmanifest"/>
      </head>
      <body className={` font-main transition-colors duration-1000 scroll-smooth w-full bg-zinc-100 dark:bg-zinc-800`}>
        <NavBar />
        {children}
        
      </body>
    </html>
  )
}
