import './globals.css';
import NavBar from './NavBar';
import Footer from './footer';

export const metadata = {
  title: 'Sheik Gulfaan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-main'>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
